create extension if not exists vector with schema extensions;

create table if not exists public.regulation_chunks (
  id bigint generated by default as identity primary key,
  passage_id text not null unique,
  title text not null default '',
  document text not null default '',
  article text not null default '',
  content text not null,
  embedding_text text not null default '',
  content_hash text not null default '',
  embedding extensions.vector(768) not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists regulation_chunks_embedding_hnsw_idx
on public.regulation_chunks
using hnsw (embedding extensions.vector_cosine_ops);

create or replace function public.match_regulation_chunks(
  query_embedding extensions.vector(768),
  match_count integer default 20
)
returns table (passage_id text, similarity double precision)
language sql stable security definer set search_path = public
as $$
  select rc.passage_id, 1 - (rc.embedding <=> query_embedding) as similarity
  from public.regulation_chunks rc
  order by rc.embedding <=> query_embedding
  limit greatest(match_count,1);
$$;
